<?php

/**
*@file
*@author Ing. Jose Manuel Santibañez Villanueva
*modulo para generar un muestrario de los albumes digitales
*@see http://www.noticiasnet.mx
*/

/**
*se implementa el hook imagecache_default_presets
* con este hook se genera un preset en imaga cache para las imagenes predeterminadas
*/
function muestrario_imagecache_default_presets() {
  $presets = array();
  $presets['muestrario_miniatura'] = array (
    'presetname' => 'muestrario_miniatura',
    'actions' =>
    array (
      0 =>
      array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' =>
        array (
          'width' => '78',
        ),
      ),
	  1 => 
	  array(
	  	'weight' => '1',
		'module' => 'imagecache',
		'action' => 'imagecache_crop',
		'data' => array('width' => '78', 'height' => '78','xoffset' => 'center', 'yoffset' => 'top'),
	  ),
    ),
  );
  return $presets;
}

/**
* implementacion del hook_init()
*se inicializan los scripts necesarios para el funcionamiento del modulo
*/
function muestrario_init(){
	$path = file_create_path("muestrario");
	file_check_directory($path, FILE_CREATE_DIRECTORY);
	drupal_add_js(drupal_get_path('module','muestrario').'/js/muestrario.js');
	drupal_add_css(drupal_get_path('module','muestrario').'/css/muestrario.css');
	module_load_include('inc', 'muestrario', 'muestrario.admin');
}


/**
*implementacion del hook_menu()
*se genera un menu dentro de store con 3 submenus
*
*/

function muestrario_menu(){
	//definimos el menu principal
	$items['admin/store/muestrario'] = array(
		'title' => t('Muestrario Album digital'),
		'description' => t('aqui puedes generar los muestrarios del album digital'),
		'page callback' => 'muestrario_main',
		'access arguments' => array('administer site configuration'),
		//'file' => 'muestrario.admin.inc',
	);
	
	//definimos la pestaña default
	$items['admin/store/muestrario/main'] = array(
		'title' => t('muestrario main'),
		'description' => t('Muestra un preview del catalogo'),
		'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => 0,
	);
	
	$items['admin/store/muestrario/catalogo'] = array(
	'title' => 'catalogo',
	'description' => 'agrega los catalogos del muestrario',
	'page callback' => 'get_muestrario_catalogo',
	'access arguments' => array('administer site configuration'),
	'type' => MENU_LOCAL_TASK,
	//'file' => 'muestrario.admin.inc',
	'weight' => 2,
	);
	
	$items['admin/store/muestrario/item'] = array(
	'title' => 'item',
	'description' => 'agrega los items del muestrario',
	'page callback' => 'get_muestrario_item',
	'access arguments' => array('administer site configuration'),
	'type' => MENU_LOCAL_TASK,
	//'file' => 'muestrario.admin.inc',
	'weight' => 2,
	);
	//direccion que controla la llamda ajax para eliminar
	$items['muestrario/ajax/delete'] =array(
	'page callback' => 'muestrario_ajax_delete',
	'type' => MENU_CALLBACK,
	'access arguments' => array('access content'),
	//'file' => 'muestrario.admin.inc',
	);
	
	return $items;
}



/**
* Implementation of hook_block()
*/
function muestrario_block($op='list', $delta=0, $edit=array()) {
	switch ($op) {
		case 'list':
			$blocks[0]['info'] = 'muestrario';//_carruseln_get_bloques_lista();//genera la lista de bloques creados en build/block
			$blocks[0]['cache'] = BLOCK_NO_CACHE;
		return $blocks;
		case 'view':
			$blocks['subject'] = '';
			$blocks['content'] = generate_catalog_view();
			//$blocks = _get_carrusel_bloque($delta);//genera el contenido de cada bloque
		return $blocks;
	}
}

