<?php

/**
*@file
*@author Ing. Jose Manuel Santibañez Villanueva
*modulo para generar un muestrario de los albumes digitales
*@see http://www.noticiasnet.mx
*/

/**
*se implementa el hook imagecache_default_presets
* con este hook se genera un preset en imaga cache para las imagenes predeterminadas
*/
function muestrario_imagecache_default_presets() {
  $presets = array();
  $presets['muestrario_miniatura'] = array (
    'presetname' => 'muestrario_miniatura',
    'actions' =>
    array (
      0 =>
      array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' =>
        array (
          'width' => '100',
        ),
      ),
	  1 => 
	  array(
	  	'weight' => '1',
		'module' => 'imagecache',
		'action' => 'imagecache_crop',
		'data' => array('width' => '100', 'height' => '90','xoffset' => 'center', 'yoffset' => 'top'),
	  ),
    ),
  );
  return $presets;
}

/**
* implementacion del hook_init()
*se inicializan los scripts necesarios para el funcionamiento del modulo
*/
function muestrario_init(){
}


/**
*implementacion del hook_menu()
*se genera un menu dentro de store con 3 submenus
*
*/

function muestrario_menu(){
	//definimos el menu principal
	$items['admin/store/muestrario'] = array(
		'title' => t('Muestrario Album digital'),
		'description' => t('aqui puedes generar los muestrarios del album digital'),
		'page callback' => 'muestrario_main',
		'access arguments' => array('administer site configuration'),
		'file' => 'muestrario.admin.inc',
	);
	
	//definimos la pestaña default
	$items['admin/store/muestrario/main'] = array(
		'title' => t('muestrario main'),
		'description' => t('Muestra un preview del catalogo'),
		'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => 0,
	);
	
	$items['admin/store/muestrario/catalogo'] = array(
	'title' => 'catalogo',
	'description' => 'agrega los catalogos del muestrario',
	'page callback' => 'get_muestrario_catalogo',
	'access arguments' => array('administer site configuration'),
	'type' => MENU_LOCAL_TASK,
	'file' => 'muestrario.admin.inc',
	'weight' => 2,
	);
	
	$items['admin/store/muestrario/item'] = array(
	'title' => 'item',
	'description' => 'agrega los items del muestrario',
	'page callback' => 'get_muestrario_item',
	'access arguments' => array('administer site configuration'),
	'type' => MENU_LOCAL_TASK,
	'file' => 'muestrario.admin.inc',
	'weight' => 2,
	);
	
	return $items;
}